"""empty message

Revision ID: 0d20ee4105a4
Revises: d53109438b4d
Create Date: 2022-07-14 00:55:34.909782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d20ee4105a4'
down_revision = 'd53109438b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('cellphone', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'cellphone')
    # ### end Alembic commands ###
