"""empty message

Revision ID: 7b85be8a6f99
Revises: f5881ccafa86
Create Date: 2022-07-14 00:06:26.775417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b85be8a6f99'
down_revision = 'f5881ccafa86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options',
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=256), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.add_column('test_question', sa.Column('is_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_question', 'is_approved')
    op.drop_table('options')
    # ### end Alembic commands ###
