"""empty message

Revision ID: 91e20f6a57f4
Revises: ca67dc5fba96
Create Date: 2022-07-14 00:18:17.800827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e20f6a57f4'
down_revision = 'ca67dc5fba96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('psychiatrist_id_of_added_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tests', 'psychiatrists', ['psychiatrist_id_of_added_by'], ['psychiatrist_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_column('tests', 'psychiatrist_id_of_added_by')
    # ### end Alembic commands ###
