"""empty message

Revision ID: ca67dc5fba96
Revises: ff9aedfa8360
Create Date: 2022-07-14 00:14:47.950258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca67dc5fba96'
down_revision = 'ff9aedfa8360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('height_inches', sa.Integer(), nullable=True),
    sa.Column('weight_kgs', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['persons.person_id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('psychiatrists',
    sa.Column('psychiatrist_id', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('available_times', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['psychiatrist_id'], ['persons.person_id'], ),
    sa.PrimaryKeyConstraint('psychiatrist_id')
    )
    op.drop_column('persons', 'height_inches')
    op.drop_column('persons', 'weight_kgs')
    op.drop_column('persons', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('persons', sa.Column('weight_kgs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('persons', sa.Column('height_inches', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('psychiatrists')
    op.drop_table('patients')
    # ### end Alembic commands ###
