"""empty message

Revision ID: d53109438b4d
Revises: ef36fa121206
Create Date: 2022-07-14 00:42:49.723996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53109438b4d'
down_revision = 'ef36fa121206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['options.option_id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.test_result_id'], ),
    sa.PrimaryKeyConstraint('test_result_id', 'option_id')
    )
    op.create_table('counselling_suggestion',
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('psychiatrist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['psychiatrist_id'], ['psychiatrists.psychiatrist_id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.test_result_id'], ),
    sa.PrimaryKeyConstraint('test_result_id', 'psychiatrist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counselling_suggestion')
    op.drop_table('answer')
    # ### end Alembic commands ###
