"""empty message

Revision ID: d9f9b07686e8
Revises: ce52e4c02a8b
Create Date: 2022-07-13 21:43:16.205971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f9b07686e8'
down_revision = 'ce52e4c02a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles2_pkey'),
    sa.UniqueConstraint('name', name='roles2_name_key')
    )
    # ### end Alembic commands ###
