"""empty message

Revision ID: deaa194f83b1
Revises: 14dfbd744cb3
Create Date: 2022-07-13 22:08:16.402113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deaa194f83b1'
down_revision = '14dfbd744cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('photo_path', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('patients',
    sa.Column('height_inches', sa.Integer(), nullable=True),
    sa.Column('weight_kgs', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['persons.person_id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    op.drop_table('persons')
    # ### end Alembic commands ###
