"""empty message

Revision ID: df6e830b47b3
Revises: d265d2249a97
Create Date: 2022-07-13 21:39:34.979490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6e830b47b3'
down_revision = 'd265d2249a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('rnd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rnd',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('genus', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table('roles')
    # ### end Alembic commands ###
