"""empty message

Revision ID: f5881ccafa86
Revises: deaa194f83b1
Create Date: 2022-07-13 23:48:12.667920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5881ccafa86'
down_revision = 'deaa194f83b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('tests',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_table('test_question',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.test_id'], ),
    sa.PrimaryKeyConstraint('test_id', 'question_id')
    )
    op.drop_table('patients')
    op.add_column('persons', sa.Column('height_inches', sa.Integer(), nullable=True))
    op.add_column('persons', sa.Column('weight_kgs', sa.Integer(), nullable=True))
    op.add_column('persons', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'location')
    op.drop_column('persons', 'weight_kgs')
    op.drop_column('persons', 'height_inches')
    op.create_table('patients',
    sa.Column('height_inches', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight_kgs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['persons.person_id'], name='patients_patient_id_fkey'),
    sa.PrimaryKeyConstraint('patient_id', name='patients_pkey')
    )
    op.drop_table('test_question')
    op.drop_table('tests')
    op.drop_table('questions')
    # ### end Alembic commands ###
